### PR TITLE
Updating addon to work with ember-cli >= 1.13.9

### PR DESCRIPTION
**Pull request by afn**
Changes based on ember-cli-coffeescript

### CODE REVIEW

**Comment by afn** [comment]
Thanks for the quick merge! Can you also push a new release to npm?

**Comment by kristianmandrup** [comment]
Will do so shortly ;)

**Comment by afn** [comment]
Looks like npm still has the old version... when you get a chance, can you bump the version and push out the new release? Thanks!

**Comment by kristianmandrup** [comment]
Just did, hope it solves any issues. I don't use ember myself since ~2014. You are welcome to take over.

**Pull request merged**
